//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.04 at 01:36:17 AM IST 
//


package com.tiaa.entity;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@XmlAccessorType(XmlAccessType.FIELD)
@JsonPropertyOrder({
    "branch",
    "orders"
})
public class Cmfoodchain {

	@JsonProperty("branch")
    protected List<Branch> branch;
	@JsonProperty("orders")
    protected Orders orders;

    public List<Branch> getBranch() {
		return branch;
	}

	public void setBranch(List<Branch> branch) {
		this.branch = branch;
	}

	public Orders getOrders() {
        return orders;
    }

    public void setOrders(Orders value) {
        this.orders = value;
    }

}
